#! /bin/sh
### BEGIN INIT INFO
# Provides:          PandaCommerce mail relay server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Relayd initscript
# Description:       This initiscript starts and stops relayd
### END INIT INFO

DAEMON=/usr/local/sbin/relayd
DESC=$($DAEMON -h 2>&1|tr -d '\n')

. /lib/lsb/init-functions

[ -x "$DAEMON" ] || exit 0
 

